development:
  adapter: postgresql
  encoding: unicode
  database: airpic_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: airpic_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: airpic_production
  pool: 5